services:

  database:
    image: postgres:15-alpine
    container_name: fraud-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-fraud_detection}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${DB_PORT:-5432}/${DB_NAME:-fraud_detection}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: fraud-ai
    restart: always
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fraud-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: