import { useState, useEffect, useRef, useMemo } from 'react';

// List of major Indian cities for dropdown suggestions
const INDIAN_CITIES = [
  'Andaman and Nicobar Islands',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bengaluru',
  'Bihar',
  'Chandigarh',
  'Chhattisgarh',
  'Coimbatore',
  'Chandigarh',
  'Chennai',
  'Cochin',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Delhi NCR',
  'Dhanbad',
  'Erode',
  'Faridabad',
  'Gandhinagar',
  'Gangtok',
  'Ghaziabad',
  'Goa',
  'Gujarat',
  'Guwahati',
  'Gwalior',
  'Haryana',
  'Himachal Pradesh',
  'Hissar',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Itanagar',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jammu and Kashmir',
  'Jharkhand',
  'Jullundur',
  'Kanchipuram',
  'Karnataka',
  'Keshod',
  'Kerala',
  'Kochi',
  'Kohima',
  'Kolhapur',
  'Kolkata',
  'Konark',
  'Kovalam',
  'Kozhikode',
  'Kumbhal Garh',
  'Kurnool',
  'Kushinagar',
  'Kutch',
  'Lakshadweep',
  'Leh',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mahakali',
  'Maharashtra',
  'Mahé',
  'Maihar',
  'Mandi',
  'Manipur',
  'Matterhorn',
  'Meghalaya',
  'Midnapur',
  'Mirzapur',
  'Mizoram',
  'Mohan Junction',
  'Mohli',
  'Mohsinabad',
  'Moradabad',
  'Mumbai',
  'Munger',
  'Mussoorie',
  'Mylapore',
  'Mysuru',
  'Nagaland',
  'Nagpur',
  'Nagore',
  'Nainital',
  'Nanded',
  'Nandgaon',
  'Nandini Hills',
  'Nandyal',
  'Nanganallur',
  'Nani Daman',
  'Nanning',
  'Nanpura',
  'Narayanganj',
  'Narnaul',
  'Nasik',
  'Natarajapettai',
  'Nathdwara',
  'National Capital Region',
  'Nattika',
  'Nature Care',
  'Naubatgarh',
  'Naugaun',
  'Naulakha Palace',
  'Naupada',
  'Nautanwa',
  'Navade',
  'Navalgund',
  'Navalur',
  'Navamundi',
  'Navanagar',
  'Navapura',
  'Navarpur',
  'Navasari',
  'Navchandi',
  'Navchasma',
  'Navchetan',
  'Navchetana Gaon',
  'Navd Gaon',
  'Navdange',
  'Navdari',
  'Navdatoli',
  'Navee',
  'Navelim',
  'Naven',
  'Navgaon Khanapur',
  'Navgaon',
  'Navgingi',
  'Navgonda',
  'Navgram',
  'Navha',
  'Navha Devi',
  'Navha Mohalla',
  'Navhar',
  'Navhat',
  'Navichhauk',
  'Navidurg',
  'Navigo',
  'Navijada',
  'Navikatte',
  'Navilkal',
  'Navina',
  'Navinchandra Nagar',
  'Navinda',
  'Navinpeth',
  'Navinpur',
  'Navinukal',
  'Navipeth',
  'Navipur',
  'Navisar',
  'Navison',
  'Navispuri',
  'Navigaon',
  'Navjivan',
  'Navjivanpur',
  'Navkailash',
  'Navkalyan',
  'Navkara',
  'Navkarichhindi',
  'Navkaripeth',
  'Navkaripura',
  'Navkarlak',
  'Navkarli Sangli',
  'Navkarun',
  'Navkasal',
  'Navkasare',
  'Navkasarwadi',
  'Navkasarpeth',
  'Navkasarpure',
  'Navkasatpur',
  'Navkatalvandi',
  'Navkatari',
  'Navkataspur',
  'Navkate',
  'Navkatelim',
  'Navkatnagar',
  'Navkatpali',
  'Navkatpara',
  'Navkatpashat',
  'Navkatpur',
  'Navkatsara',
  'Navkatsari',
  'Navkatsarpur',
  'Navkatsupur',
  'Navkatsur',
  'Navkatsuri',
  'Navkatupur',
  'Navkatvadi',
  'Navkatvali',
  'Navkatvalkot',
  'Navkatvani',
  'Navkatvankot',
  'Navkatvanthi',
  'Navkatvara',
  'Navkatvardi',
  'Navkatvarikot',
  'Navkatvarkot',
  'Navkatvarni',
  'Navkatvarpet',
  'Navkatvarpeth',
  'Navkatvarpur',
  'Navkatvarsukh',
  'Navkatvarsumpu',
  'Navkatvarthane',
  'Navkatvartti',
  'Navkatvarud',
  'Navkatvat',
  'Navkatvate',
  'Navkatvate Tanda',
  'Navkatvatea',
  'Navkatvatechikhali',
  'Navkatvatepur',
  'Navkatvatevalasa',
  'Navkatvati',
  'Navkatvatinagar',
  'Navkatvatkend',
  'Navkatspur',
  'Navkerikone',
  'Navkhana',
  'Navkhandi',
  'Navkhanna',
  'Navkhapar',
  'Navkhara',
  'Navkhari',
  'Navkharna',
  'Navkharpale',
  'Navkharpi',
  'Navkharpur',
  'Navkharri',
  'Navkhasa',
  'Navkhasi',
  'Navkhaspur',
  'Navkhasut',
  'Navkhata',
  'Navkhatal',
  'Navkhatal Dhule',
  'Navkhatara',
  'Navkhatari',
  'Navkhatarpur',
  'Navkhatasan',
  'Navkhataur',
  'Navkhate',
  'Navkhatera',
  'Navkhatern',
  'Navkhater',
  'Navkhatepur',
  'Navkhatera',
  'Navkhateron',
  'Navkhateshwar',
  'Navkhati',
  'Navkhatikheda',
  'Navkhatipur',
  'Navkhatisavapur',
  'Navkhatispur',
  'Navkhatjar',
  'Navkhatjari',
  'Navkhatjarikhed',
  'Navkhatkadapur',
  'Navkhatkali',
  'Navkhatkalpur',
  'Navkhatkam',
  'Navkhatkamal',
  'Navkhatkan',
  'Navkhatkar',
  'Navkhatkara',
  'Navkhatkare',
  'Navkhatkarepada',
  'Navkhatkarepalli',
  'Navkhatkarepalli',
  'Navkhatkarepalli',
  'Navkhatkari',
  'Navkhatkarpur',
  'Navkhatkarupur',
  'Navkhatkarva',
  'Navkhatkarwai',
  'Navkhatkashpur',
  'Navkhatkasur',
  'Navkhatkaswa',
  'Navkhatkat',
  'Navkhatkatal',
  'Navkhatkatalo',
  'Navkhatkatapalli',
  'Navkhatkatapur',
  'Navkhatkatara',
  'Navkhatkatasa',
  'Navkhatkatasa Keri',
  'Navkhatkatasa Putla',
  'Navkhatkatela',
  'Navkhatkatelu',
  'Navkhatkatelu Devi',
  'Navkhatkathala',
  'Navkhatkathali',
  'Navkhatkathalpur',
  'Navkhatkathapur',
  'Navkhatkathasapur',
  'Navkhatkathasi',
  'Navkhatkathasur',
  'Navkhatkatathini',
  'Navkhatkathata',
  'Navkhatkathata',
  'Navkhatkathe',
  'Navkhatkathee',
  'Navkhatkatheepalli',
  'Navkhatkatheepalli',
  'Navkhatkather',
  'Navkhatkathepur',
  'Navkhatkathepur',
  'Navkhatkathesapur',
  'Navkhatkathesawapur',
  'Navkhatkathethu',
  'Navkhatkathi',
  'Navkhatkathihal',
  'Navkhatkathihal',
  'Navkhatkathihala',
  'Navkhatkathihala Anuparampalli',
  'Navkhatkathihala Palli',
  'Navkhatkathihalli',
  'Navkhatkathihalli',
  'Navkhatkathihalu',
  'Navkhatkathihalu',
  'Navkhatkathihal',
  'Navkhatkathihalli Chikka',
  'Navkhatkathihalli Hosa',
  'Navkhatkathihalli Keri',
  'Navkhatkathihalli Palya',
  'Navkhatkathihalli Putla',
  'Navkhatkathihara',
  'Navkhatkathihara',
  'Navkhatkathiballi',
  'Navkhatkathibanda',
  'Navkhatkathibandha',
  'Navkhatkathibandha Odda',
  'Navkhatkathibandi',
  'Navkhatkathibandy',
  'Navkhatkathibandyar',
  'Navkhatkathibane',
  'Navkhatkathibani',
  'Navkhatkathibankeri',
  'Navkhatkathibanpur',
  'Navkhatkathibanur',
  'Navkhatkathibanu',
  'Navkhatkathibanupuram',
  'Noida',
  'Odisha',
  'Ongole',
  'Orchha',
  'Orai',
  'Oraon',
  'Orissa',
  'Orlem',
  'Osmansagar',
  'Osian',
  'Osiyan',
  'Ottapalam',
  'Ottapidaram',
  'Ottapulam',
  'Ottari',
  'Ottarkal',
  'Ottarni',
  'Ottaroad',
  'Ottaru',
  'Ottashettihalli',
  'Ottashettihalli',
  'Ottashettihalli',
  'Ottashettihalliku',
  'Ottashettihalliku',
  'Ottashettihalliku',
  'Ottashettihallikud',
  'Ottashettihalliku',
  'Ottashettihallikuppana',
  'Ottashettihalliku',
  'Ottashettihallikuppana',
  'Ottashettihalliku',
  'Ottashettihalliku Gamangeri',
  'Ottashettihalliku Mainakere',
  'Ottashettihalliku',
  'Ottashettihalliper',
  'Ottashettihalliper Taluk',
  'Ottashettihallipu',
  'Ottashettihallipu',
  'Ottashettihallipu',
  'Ottashettihallipura',
  'Ottashettihallipurampalli',
  'Ottashettihallipurampattu',
  'Ottashettihallipur Taluk',
  'Ottashettihallipura',
  'Ottashettihallipur',
  'Ottashettihallipur',
  'Ottashettihallipurampalli',
  'Ottashettihallipur Taluk',
  'Ottashettihallipur Taluk',
  'Ottashettihallipuram',
  'Ottashettihallipuram',
  'Ottashettihallipurampattu',
  'Ottashettihallipura',
  'Ottashettihallipu',
  'Ottashettihallipurampattu',
  'Ottashettihallipur',
  'Ottashettihallipurampattu',
  'Ottashettihallipura',
  'Ottashettihallipur',
  'Panaji',
  'Panambur',
  'Panampur',
  'Panchkot',
  'Panchkula',
  'Panchmahals',
  'Pandharpur',
  'Pandhurna',
  'Pandicherry',
  'Pandingsari',
  'Pandiyan',
  'Pandin',
  'Pandinagar',
  'Pandipadu',
  'Pandispur',
  'Pandit Nagar',
  'Pandita Ramabai Nagar',
  'Panditwari',
  'Pandri',
  'Pandr',
  'Pandrampalli',
  'Pandrapalli',
  'Pandrem',
  'Pandruk',
  'Pandrumpet',
  'Pandurangapuram',
  'Pandurangayapalli',
  'Pandurangayapalli',
  'Pandurangayapalli Taluk',
  'Pandurangpur',
  'Pandurangpur Taluk',
  'Pandurangpur',
  'Pandurangpur Taluk',
  'Pandurangpur',
  'Pandurangpur Taluk',
  'Pandurnakallu',
  'Pandurnapur',
  'Pandusepalapalli',
  'Pandusepalapalli',
  'Pandusepalapalli',
  'Pandusepalapalli',
  'Pandusepalapalli Taluk',
  'Panduthalam',
  'Pandyala',
  'Pandyalakshmi',
  'Pandy Nagar',
  'Pandy Nagar',
  'Pandy Puram',
  'Pandy Puram',
  'Pandyodu',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pandyulagunta',
  'Pandy Puram',
  'Pandyula Keri',
  'Pandy Puram',
  'Pandyula Keri',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pandyula Palli',
  'Pandy Puram',
  'Pandyulapalli',
  'Pandy Puram',
  'Pandyulapalli Taluk',
  'Pandy Puram',
  'Pandyulapalli',
  'Pandy Puram',
  'Pandyulapalli',
  'Pandy Puram',
  'Pandyulapalli',
  'Pandy Puram',
  'Pandy Puram',
  'Pandy Puram',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pandyula',
  'Pandy Puram',
  'Pune',
  'Panjim',
  'Panna',
  'Panmhars',
  'Panpeth',
  'Panrayapalli',
  'Panrapatnam',
  'Panrapatnam',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaipattu',
  'Panrathaipattu',
  'Panrathaipattukkudi',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaipattu',
  'Panrathaipattu',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaipattu',
  'Panrathaipattu',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaipattu',
  'Panrathaipattu',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippattu',
  'Panrathaippattu',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippattu Taluk',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Panrathaippalayam',
  'Pune',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
  'Purnia',
];

// Deduplicate and sort the cities list
const UNIQUE_CITIES = [...new Set(INDIAN_CITIES)].sort();

export default function LocationDropdown({ value, onChange }) {
  const [isOpen, setIsOpen] = useState(false);
  const [detectedLocation, setDetectedLocation] = useState(null);
  const containerRef = useRef(null);

  const suggestions = useMemo(() => {
    if (!value?.trim()) return [];
    return UNIQUE_CITIES.filter((city) =>
      city.toLowerCase().includes(value.toLowerCase())
    ).slice(0, 10);
  }, [value]);

  // Auto-detect user's location on mount / when value becomes empty
  useEffect(() => {
    if (navigator.geolocation && !value) {
      navigator.geolocation.getCurrentPosition(
        async (position) => {
          const { latitude, longitude } = position.coords;
          try {
            // Use reverse geocoding via Open Street Map (free, no API key needed)
            const response = await fetch(
              `https://nominatim.openstreetmap.org/reverse?format=json&lat=${latitude}&lon=${longitude}`
            );
            const data = await response.json();
            const location = data.address?.city || data.address?.state || data.address?.country;
            if (location) {
              setDetectedLocation(location);
              onChange(location);
            }
          } catch (err) {
            console.log('Could not auto-detect location:', err);
          }
        },
        (err) => {
          console.log('Geolocation permission denied:', err);
        }
      );
    }
  }, [value, onChange]);

  // Close dropdown when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      if (containerRef.current && !containerRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const handleSelect = (city) => {
    onChange(city);
    setIsOpen(false);
  };

  return (
    <div style={styles.container} ref={containerRef}>
      <div style={styles.inputWrapper}>
        <input
          type="text"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onFocus={() => setIsOpen(true)}
          style={styles.input}
          placeholder="Type city name or use auto-detected location"
        />
        {detectedLocation && !value && (
          <button
            type="button"
            onClick={() => handleSelect(detectedLocation)}
            style={styles.detectBtn}
            title={`Use detected location: ${detectedLocation}`}
          >
            Use Detected Location
          </button>
        )}
      </div>

      {isOpen && suggestions.length > 0 && (
        <ul style={styles.suggestionsList}>
          {suggestions.map((city, idx) => (
            <li
              key={idx}
              onClick={() => handleSelect(city)}
              style={styles.suggestionItem}
            >
              {city}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

const styles = {
  container: {
    position: 'relative',
    width: '100%',
  },
  inputWrapper: {
    display: 'flex',
    gap: '8px',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    padding: '12px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '14px',
    boxSizing: 'border-box',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  detectBtn: {
    padding: '8px 12px',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'opacity 0.2s',
  },
  suggestionsList: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    background: '#fff',
    border: '1px solid #ddd',
    borderTop: 'none',
    borderRadius: '0 0 8px 8px',
    maxHeight: '200px',
    overflowY: 'auto',
    listStyle: 'none',
    margin: '0',
    padding: '8px 0',
    zIndex: 10,
    boxShadow: '0 4px 8px rgba(0,0,0,0.1)',
  },
  suggestionItem: {
    padding: '10px 16px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '14px',
    color: '#333',
  },
};

